import { Router } from 'express';
import * as adminController from '../controllers/admin.controller.js';
import { authenticate } from '../middleware/authenticate.js';
import { requireRole } from '../middleware/requireRole.js';
import { asyncHandler } from '../middleware/asyncHandler.js';

export const adminRoutes = Router();
adminRoutes.use(authenticate, requireRole('admin'));

adminRoutes.get('/overview', asyncHandler(adminController.getOverview));
adminRoutes.get('/team', asyncHandler(adminController.getTeam));
adminRoutes.post('/team', asyncHandler(adminController.createTeamMember));
adminRoutes.get('/site-images', asyncHandler(adminController.getSiteImages));
adminRoutes.put('/site-images', asyncHandler(adminController.updateSiteImage));
adminRoutes.get('/impact-records/draft', asyncHandler(adminController.getImpactRecordDraft));
adminRoutes.get('/impact-records/drafts', asyncHandler(adminController.getImpactRecordDrafts));
adminRoutes.post('/impact-records', asyncHandler(adminController.saveImpactRecord));
adminRoutes.post('/impact-records/batch', asyncHandler(adminController.saveImpactRecordsBatch));
adminRoutes.post('/impact-records/generate', asyncHandler(adminController.generateImpactText));
adminRoutes.get('/funds/unallocated', asyncHandler(adminController.getUnallocatedFunds));
adminRoutes.patch('/donations/:id/assign-program', asyncHandler(adminController.assignDonationProgram));

adminRoutes.get('/programs', asyncHandler(adminController.getPrograms));
adminRoutes.post('/programs', asyncHandler(adminController.createProgram));
adminRoutes.patch('/programs/:id', asyncHandler(adminController.updateProgram));
adminRoutes.delete('/programs/:id', asyncHandler(adminController.deleteProgram));
adminRoutes.get('/events', asyncHandler(adminController.getEvents));
adminRoutes.post('/events', asyncHandler(adminController.createEvent));
adminRoutes.get('/events/:id', asyncHandler(adminController.getEventDetail));
adminRoutes.patch('/events/:id', asyncHandler(adminController.updateEvent));
adminRoutes.patch('/events/:id/checklist', asyncHandler(adminController.updateChecklistItem));
adminRoutes.delete('/events/:id', asyncHandler(adminController.deleteEvent));
adminRoutes.get('/volunteers', asyncHandler(adminController.getVolunteers));
adminRoutes.get('/beneficiaries', asyncHandler(adminController.getBeneficiaries));
adminRoutes.post('/beneficiaries', asyncHandler(adminController.createBeneficiary));
adminRoutes.patch('/beneficiaries/:id', asyncHandler(adminController.updateBeneficiary));
adminRoutes.delete('/beneficiaries/:id', asyncHandler(adminController.deleteBeneficiary));
adminRoutes.get('/beneficiaries/:id/visits', asyncHandler(adminController.getBeneficiaryVisits));
adminRoutes.post('/beneficiaries/:id/visits', asyncHandler(adminController.logBeneficiaryVisit));
adminRoutes.delete('/beneficiaries/:id/visits/:visitId', asyncHandler(adminController.deleteBeneficiaryVisit));
adminRoutes.get('/donors', asyncHandler(adminController.getDonors));
adminRoutes.get('/donations', asyncHandler(adminController.getDonations));
adminRoutes.post('/donations/:id/verify', asyncHandler(adminController.verifyDonation));
